name: CI

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
    watch:
      types: started   


jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      # 项目初始
     - name: Code Checkout
       uses: actions/checkout@master
