name: CI

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
    watch:
      types: started   

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1.1.2
      env:
        SOURCE_REPO: "git@github.com:yfdoor/OpenWrt-CI.git"
        SOURCE_BRANCH: "match"
        DESTINATION_REPO: "git@gitee.com:yfdor/OpenWrt-CI.git"
        DESTINATION_BRANCH: "master"
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
