name: CI

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
    watch:
      types: started   


jobs:
  git-repo-backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: git-repo-backup
      uses: jenkins-zh/git-backup-actions@v0.0.1
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GITEE_TOKEN }}
        TARGET_GIT: "git@gitee.com:yfdoor/OpenWrt-CI.git"
