name: CI

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
    watch:
      types: started   

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hub Mirror Action.
        uses: Yikun/hub-mirror-action@v0.02
        with:
          src: github/yfdoor/OpenWrt-CI
          dst: gitee/yfdoor/OpenWrt-CI
          # dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
