# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: Download

# 触发条件
on:
  push:
  #    branches:
  #      - master
    paths:
      - 'Download.URL'
  # schedule:
  #   - cron: 0 0 1/3 * *
  # watch:
  #   types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      # 项目初始
      - name: Code Checkout
        uses: actions/checkout@master

     # 下载软件
      - name: Download Package
        run: |
          export DOWNLOAD_PATH="$(cat Download.URL)"
          rm -rf download
          mkdir -p download/tmp
          wget --content-disposition -P download/tmp -o DownloadLog.log $DOWNLOAD_PATH
          ls download/tmp | xargs echo > download/filename.txt    
          export FNAME="$(cat download/filename.txt)"
          echo $DOWNLOAD_PATH >> download/filename.txt
          cd download
          cp filename.txt tmp/filename.txt
          echo $FNAME
          zip -r $FNAME.zip -s 100m tmp
          rm -rf tmp

     # 更新分支
      - name: Upload Branch
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config user.name "yfdoor"
          git config user.email "yfdoor@github.com"
          git add .
          git commit -m "Update new package"
          git push
